package statuses

const (
	BOOKED    = "BOOKED"
	TICKETED  = "TICKETED"
	CANCELED  = "CANCELED"
	ERROR     = "ERROR"
	EXPIRED   = "EXPIRED"
	INITIATED = "INITIATED"
	PAID      = "PAID"

	DEFAULT_MEAL = "DEFAULT_MEAL"

	FLIGHT_DEPARTURE = "DEPARTURE"
	FLIGHT_RETURN    = "RETURN"

	INFANT = "INFANT"
	ADULT  = "ADULT"
	CHILD  = "CHILD"

	INSURANCE_CODE = "INSURANCE"

	ADDONS_MEAL    = "MEALS"
	ADDONS_BAGGAGE = "BAGGAGE"
	ADDONS_SEAT    = "SEAT"

	TRANSACTION_FLIGHT = "FLIGHT"
	TRANSACTION_HOTEL  = "HOTEL"

	TITLE_MR  = "MR"
	TITLE_MRS = "MRS"
	TITLE_MS  = "MS"

	TITLE_MSTR = "MSTR"
	TITLE_MISS = "MISS"

	TITLE_INF = "MS"

	PROMO_USED    = "USED"
	PROMO_CLAIMED = "CLAIMED"

	LANG_EN = "EN"
	LANG_ID = "ID"
)
